### ISSUE TITLE
Feature Request: Add Support for cAdvisor-like Metrics Format

### ISSUE THREAD

**Issue by pavlozt** [davidborzek/docker-exporter#94]
Existing monitoring dashboards (e.g., Grafana) built for cAdvisor metrics cannot be reused directly with this project. Users must recreate visualizations, increasing adoption friction and setup time.

 I suggest adding a new optional metrics format mimicking cAdvisor's structure, or a compatibility layer/translator converting native metrics to cAdvisor's schema.

I would be very enthusiastic to participate in testing such a feature.

**Comment by davidborzek** [comment]
Quick update on this.

I won't ship a full cAdvisor emulation layer, but the next release reworks the metrics to be cAdvisor-aligned, so you can reuse most dashboards via relabeling instead.

CPU is now `docker_container_cpu_usage_seconds_total` (counter, use `rate()`); network/fs/memory follow cAdvisor names too. The only differences are the `docker_` prefix and the `network` label (cAdvisor calls it `interface`). I'd rewrite both in your scrape config:

```yaml
metric_relabel_configs:
  - source_labels: [__name__]
    regex: 'docker_container_(.*)'
    target_label: __name__
    replacement: 'container_${1}'
  - source_labels: [network]
    target_label: interface
```

Container labels are available as `container_label_*` (via `--container-label` or the `docker-exporter.exposed-labels` label).

Not covered: `machine_*`, per-mode/throttling CPU, per-device fs, the memory breakdown (`working_set`/`rss`/`cache`), and k8s labels — dashboards using those won't fully resolve. If you need those, a PR would be welcome.
